In [1]:
import pandas as pd
import polars as pl
import numpy as np
import os, gc
from tqdm.auto import tqdm
from matplotlib import pyplot as plt
import pickle

import torch
import torch.nn as nn
import torch.nn.functional as F
from pytorch_lightning import LightningDataModule, LightningModule, Trainer
from pytorch_lightning.callbacks import EarlyStopping, ModelCheckpoint, Timer

import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, DataLoader

import optuna

from sklearn.metrics import r2_score
from sklearn.ensemble import VotingRegressor

import warnings

warnings.filterwarnings("ignore")
pd.options.display.max_columns = None

/Users/johnny/Library/CloudStorage/OneDrive-Personal/py/JaneStreet2024/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
class CONFIG:
    seed = 42
    target_col = "responder_6"
    # feature_cols = ["symbol_id", "time_id"] + [f"feature_{idx:02d}" for idx in range(79)]+ [f"responder_{idx}_lag_1" for idx in range(9)]
    feature_cols = [f"feature_{idx:02d}" for idx in range(79)] + [
        f"responder_{idx}_lag_1" for idx in range(9)
    ]

In [3]:
valid = pl.scan_parquet("validation.parquet").collect()
train = pl.scan_parquet("training.parquet").collect()
train = pl.concat([train, valid])
del valid
train = train.sort(["date_id", "time_id"])
train = train.with_columns([
    pl.col(col).forward_fill().over('symbol_id') for col in CONFIG.feature_cols
])

train = train.with_columns([
    pl.col(col).backward_fill().over('symbol_id') for col in CONFIG.feature_cols
])

# Fill any remaining nulls with zero
train = train.fill_null(0)

In [4]:
# train up to date_id 1600
valid = train.filter(pl.col("date_id") >= 1600)
train = train.filter(pl.col("date_id") < 1600)

X_train = train[CONFIG.feature_cols]
y_train = train[CONFIG.target_col]
w_train = train["weight"]
X_valid = valid[CONFIG.feature_cols]
y_valid = valid[CONFIG.target_col]
w_valid = valid["weight"]
del train, valid
X_train.head()

shape: (5, 88)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ feature_0 ┆ feature_0 ┆ feature_0 ┆ feature_0 ┆ … ┆ responder ┆ responder ┆ responder ┆ responde │
│ 0         ┆ 1         ┆ 2         ┆ 3         ┆   ┆ _5_lag_1  ┆ _6_lag_1  ┆ _7_lag_1  ┆ r_8_lag_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 1        │
│ f32       ┆ f32       ┆ f32       ┆ f32       ┆   ┆ f32       ┆ f32       ┆ f32       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.458568  ┆ -0.05264  ┆ -0.044876 ┆ 0.124223  ┆ … ┆ 0.241938  ┆ -0.035311 ┆ 0.018396  ┆ -0.04954 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ 0.111398  ┆ 0.500473  ┆ 0.083353  ┆ 0.395555  ┆ … ┆ 0.586496  ┆ 0.023053  ┆ 0.057525  ┆ 0.054095 │
│ 0.536855  ┆ 0.309993  ┆ 0.015098  ┆ 0.318689  ┆ … ┆ 0.328058  ┆ -0.279246 ┆ -0.160299 ┆ -0.81783 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│ -0.016845 ┆ -0.104391 ┆ -0.202445 ┆ 0.404921  ┆ … ┆ 0.568287  ┆ -0.144531 ┆ -0.038709 ┆ -0.26262 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ 0.269194  ┆ -0.088913 ┆ -0.436358 ┆ -0.025382 ┆ … ┆ -0.475962 ┆ 0.354286  ┆ 0.214541  ┆ 0.714783 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
X_valid.head()

shape: (5, 88)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ feature_0 ┆ feature_0 ┆ feature_0 ┆ feature_0 ┆ … ┆ responder ┆ responder ┆ responder ┆ responde │
│ 0         ┆ 1         ┆ 2         ┆ 3         ┆   ┆ _5_lag_1  ┆ _6_lag_1  ┆ _7_lag_1  ┆ r_8_lag_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 1        │
│ f32       ┆ f32       ┆ f32       ┆ f32       ┆   ┆ f32       ┆ f32       ┆ f32       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.012978  ┆ -0.062717 ┆ -0.464518 ┆ 0.25121   ┆ … ┆ 1.666419  ┆ 0.485476  ┆ 0.2579    ┆ 0.837682 │
│ -0.020206 ┆ 0.279361  ┆ -0.906437 ┆ -0.046471 ┆ … ┆ 0.253797  ┆ 0.133441  ┆ 0.092562  ┆ 0.344782 │
│ 0.124872  ┆ 0.613503  ┆ -0.44366  ┆ -0.329957 ┆ … ┆ 0.696548  ┆ 0.042677  ┆ 0.047034  ┆ 0.079025 │
│ -0.077826 ┆ 0.128762  ┆ 0.068585  ┆ 0.037601  ┆ … ┆ -0.200535 ┆ 0.162626  ┆ 0.155354  ┆ 0.329953 │
│ 0.501302  ┆ 0.056138  ┆ -0.383123 ┆ -0.527236 ┆ … ┆ 0.205143  ┆ 0.252539  ┆ 0.13703   ┆ 0.443662 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
# Custom R2 metric for validation
def r2_val(y_true, y_pred, sample_weight):
    r2 = 1 - np.average((y_pred - y_true) ** 2, weights=sample_weight) / (np.average((y_true) ** 2, weights=sample_weight) + 1e-38)
    return r2


class NN(LightningModule):
    def __init__(self, input_dim, hidden_dims, dropouts, lr, weight_decay, leak, batch_norm=True, activation='relu', lr_scheduler='cos_decay'):        
        super().__init__()
        self.save_hyperparameters()
        layers = []
        in_dim = input_dim
        for i, hidden_dim in enumerate(hidden_dims):
            layers.append(nn.Linear(in_dim, hidden_dim))
            if batch_norm:
                layers.append(nn.BatchNorm1d(hidden_dim))  # Use hidden_dim here
            # Activation function
            if activation == 'relu':
                layers.append(nn.ReLU())
            elif activation == 'silu':
                layers.append(nn.SiLU())
            elif activation == 'gelu':
                layers.append(nn.GELU())
            elif activation == 'elu':
                layers.append(nn.ELU())
            elif activation == 'leaky_relu':
                layers.append(nn.LeakyReLU(leak))
            elif activation == 'tanh':
                layers.append(nn.Tanh())
            elif activation == 'sigmoid':
                layers.append(nn.Sigmoid())
            # Dropout
            if i < len(dropouts):
                layers.append(nn.Dropout(dropouts[i]))
            # Update in_dim for the next layer
            in_dim = hidden_dim
        # Final output layer
        layers.append(nn.Linear(in_dim, 1))
        # Consider whether to include an activation function here
        # layers.append(nn.Tanh())  # Only if appropriate for your problem
        self.model = nn.Sequential(*layers)
        self.lr = lr
        self.weight_decay = weight_decay
        self.validation_step_outputs = []
        self.lr_scheduler = lr_scheduler

    def forward(self, x):
        return 5 * self.model(x).squeeze(-1)

    def training_step(self, batch):
        x, y, w = batch
        y_hat = self(x)
        loss = F.mse_loss(y_hat, y, reduction='none') * w
        loss = loss.mean()
        self.log('train_loss', loss, on_step=False, on_epoch=True, batch_size=x.size(0))
        return loss

    def validation_step(self, batch):
        x, y, w = batch
        y_hat = self(x)
        loss = F.mse_loss(y_hat, y, reduction='none') * w
        loss = loss.mean()
        self.log('val_loss', loss, on_step=False, on_epoch=True, batch_size=x.size(0))
        self.validation_step_outputs.append((y_hat, y, w))
        return loss

    def on_validation_epoch_end(self):
        if self.trainer.sanity_checking:
            self.validation_step_outputs.clear()
            return
        y = torch.cat([x[1] for x in self.validation_step_outputs]).cpu().numpy()
        prob = torch.cat([x[0] for x in self.validation_step_outputs]).cpu().numpy()
        weights = torch.cat([x[2] for x in self.validation_step_outputs]).cpu().numpy()
        val_r_square = r2_val(y, prob, weights)
        self.log("val_r_square", val_r_square, prog_bar=True, on_step=False, on_epoch=True)
        self.validation_step_outputs.clear()

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=self.lr, weight_decay=self.weight_decay)
        if self.lr_scheduler == 'cos_decay':
            scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=self.trainer.max_epochs, eta_min=1e-6, last_epoch=-1)
        else:
            scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.316, patience=5,
                                                               verbose=True)
        return {
            'optimizer': optimizer,
            'lr_scheduler': {
                'scheduler': scheduler,
                'monitor': 'val_loss',
            }
        }

    def on_train_epoch_end(self):
        if self.trainer.sanity_checking:
            return
        epoch = self.trainer.current_epoch
        metrics = {k: v.item() if isinstance(v, torch.Tensor) else v for k, v in self.trainer.logged_metrics.items()}
        formatted_metrics = {k: f"{v:.5f}" for k, v in metrics.items()}
        print(f"Epoch {epoch}: {formatted_metrics}")

def objective(trial):
    layers = trial.suggest_int("layers", 1, 6)
    hidden_dims = [trial.suggest_int(f"hidden_dim_{i}", 64, 256) for i in range(layers)]
    dropouts = [trial.suggest_float(f"dropout_{i}", 0.1, 0.5) for i in range(layers)]
    batch_norm = trial.suggest_categorical("batch_norm", [True, False])
    lr = trial.suggest_float("lr", 1e-4, 1e-2, log=True)
    lr_scheduler = trial.suggest_categorical("lr_scheduler", ['cos_decay', 'plateau'])
    activation = trial.suggest_categorical("activation", ['relu', 'silu', 'gelu', 'elu', 'leaky_relu', 'tanh', 'sigmoid'])
    weight_decay = trial.suggest_float("weight_decay", 1e-5, 1e-3, log=True)
    leak = trial.suggest_float("leak", 0.01, 0.5)
    model = NN(
        input_dim=len(CONFIG.feature_cols),
        hidden_dims=hidden_dims,
        dropouts=dropouts,
        lr=lr,
        weight_decay=weight_decay,
        leak=leak,
        batch_norm=batch_norm,
        activation=activation,
        lr_scheduler=lr_scheduler
    )
    # epochs = trial.suggest_int("epochs", 10, 500)
    epochs = 8
    trainer = Trainer(max_epochs=epochs, devices=1, accelerator='mps', logger=False, callbacks=[EarlyStopping(monitor='val_loss', patience=4)])
    trainer.fit(model, train_dataloader, val_dataloader)
    return trainer.callback_metrics["val_r_square"].item()

In [ ]:
class CustomDataset(Dataset):
    def __init__(self, X, y, w):
        self.X = X
        self.y = y
        self.w = w

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx], self.w[idx]

X_train_tensor = torch.FloatTensor(X_train.to_numpy())
y_train_tensor = torch.FloatTensor(y_train.to_numpy())
w_train_tensor = torch.FloatTensor(w_train.to_numpy())

X_valid_tensor = torch.FloatTensor(X_valid.to_numpy())
y_valid_tensor = torch.FloatTensor(y_valid.to_numpy())
w_valid_tensor = torch.FloatTensor(w_valid.to_numpy())

train_dataset = CustomDataset(X_train_tensor, y_train_tensor, w_train_tensor)
val_dataset = CustomDataset(X_valid_tensor, y_valid_tensor, w_valid_tensor)

train_dataloader = DataLoader(train_dataset, batch_size=2048, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=2048, shuffle=False)

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

print(study.best_params)

[I 2024-11-27 11:38:59,556] A new study created in memory with name: no-name-8b1ec228-8f74-489b-8493-4bac85c7373c
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name  | Type       | Params | Mode
---------------------------------------------
0 | model | Sequential | 196 K  | train
---------------------------------------------
196 K     Trainable params
0         Non-trainable params
196 K     Total params
0.787     Total estimated model params size (MB)
22        Modules in train mode
0         Modules in eval mode

Epoch 0:   0%|          | 0/8997 [00:00<?, ?it/s]

* Do k-fold cv after finding params.
* test out continuing the training